### ISSUE TITLE
READ THIS BEFORE CREATING ISSUE

### ISSUE THREAD

**Issue by wtrocki** [aerogear/aerogear-digger#18]
AeroGear project is using open jira system for issue tracking. 

To see list of available issues go to:
https://issues.jboss.org/projects/AGDIGGER/issues

To create issue in jira you would need to login (you can use your google or github account to do so)

**Comment by jcesarmobile** [comment]
You can't view this issue
It may have been deleted or you don't have permission to view it.

**Comment by wtrocki** [comment]
Oh.. I think this was really really old times where we were trying to force people to use jira, which was very very bad thing to do IMHO. 
Feel free to create issue in github and our team will make sure that we have jira for it.

**Comment by jcesarmobile** [comment]
just wanted to see current issues, I'm not using it at the moment.

**Comment by wtrocki** [comment]
@jcesarmobile We use now AeroGear for everything (https://issues.jboss.org/projects/AEROGEAR/issues)

However, this project is not under active maintenance. 
There are really nice pipeliens for Jenkins and Cordova that you can reuse, but the fact is that this was only used internally for some time and then there was a decision to move from community digger (this repository) to OpenShift based build system.
